# Generated by Django 3.0.5 on 2020-05-01 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=75, verbose_name='Descrição')),
                ('amount', models.FloatField(verbose_name='Quantidade')),
                ('unit', models.CharField(blank=True, max_length=10, null=True, verbose_name='Unidade')),
                ('brand', models.CharField(blank=True, max_length=30, null=True, verbose_name='Marca')),
                ('details', models.CharField(blank=True, max_length=150, null=True, verbose_name='Detalhes')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Observações')),
            ],
        ),
    ]
