# Generated by Django 3.0.5 on 2020-05-01 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lista', models.CharField(max_length=30, verbose_name='Nome da Lista')),
                ('produtos', models.ManyToManyField(to='product.Product', verbose_name='Produtos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lista de Compras',
                'verbose_name_plural': 'Lista de Compras',
            },
        ),
    ]
